### GET request to example server
GET https://api.odcloud.kr/api/15109950/v1/uddi:1f78fe49-78b4-4784-a5f0-e2c8a60515b4?page=1&perPage=10&serviceKey=NaiSxC8Cyo20WmSz5o6DumB04ifAN1zA1mLenlEcrzkvrqCCFJyk9YeiN7l0ZkALF5LQS4g88kK5MjOr%2F8NBow%3D%3D
###